name: habit_tracking_test
description: A new Flutter project for demonstration purposes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.3
  another_flushbar: ^1.10.22
  implicitly_animated_reorderable_list: ^0.4.0

  # Functional programming
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.27.0
  kt_dart: ^0.9.1

  # State management
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.17.0
  provider: ^5.0.0

  # Auto-gen
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  injectable: ^1.4.1
  auto_route: ^2.2.0

  # Tools and Network
  uuid: ^3.0.4
  dio: ^4.0.0
  connectivity: ^3.0.4

  # Local database
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  lint: ^1.5.3

  # Auto-gen
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  auto_route_generator: ^2.1.0
  json_serializable: ^4.1.2
  hive_generator: ^1.1.0

  # Build
  build_runner: ^2.0.3

flutter:
  uses-material-design: true

